version: "3"

services:

  db:
    image: mysql:latest
    container_name: jobapp_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=webapp
    ports:
      - "3306:3306"
    volumes:
      - data-mysql:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: jobapp_nginx
    ports:
      - "80:80"
    volumes:
      - ./webapp:/var/www/webapp
      - ./build/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    links:
      - php
  php:
    build:
      context: ./build/php-with-composer
    container_name: jobapp_php
    expose:
      - "9000"
    volumes:
      - ./webapp:/var/www/webapp
    working_dir: /var/www/webapp
    links:
      - db

volumes:
  data-mysql: {}
